services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    command: bash docker/app/start.sh

  db:
    image: postgres:18
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: