<h1 class="mb-5">Сайты</h1>

<table class="table table-bordered table-hover" data-test="urls">
    <thead>
    <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Дата создания</th>
        <th>Код ответа</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($urls as $url): ?>
        <tr>
            <td><?= htmlspecialchars((string) $url['id']) ?></td>
            <td>
                <a href="/urls/<?= htmlspecialchars((string) $url['id']) ?>">
                    <?= htmlspecialchars($url['name']) ?>
                </a>
            </td>
            <td><?= htmlspecialchars($url['created_at']) ?></td>
            <td></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
