<h1 class="mb-5">Сайт: <?= htmlspecialchars($url['name']) ?></h1>

<div class="table-responsive mb-5">
    <table class="table table-bordered table-hover" data-test="url">
        <tbody>
        <tr>
            <td>ID</td>
            <td><?= htmlspecialchars((string) $url['id']) ?></td>
        </tr>
        <tr>
            <td>Имя</td>
            <td><?= htmlspecialchars($url['name']) ?></td>
        </tr>
        <tr>
            <td>Дата создания</td>
            <td><?= htmlspecialchars($url['created_at']) ?></td>
        </tr>
        </tbody>
    </table>
</div>

<h2 class="mb-3">Проверки</h2>

<table class="table table-bordered table-hover" data-test="checks">
    <thead>
    <tr>
        <th>ID</th>
        <th>Код ответа</th>
        <th>h1</th>
        <th>title</th>
        <th>description</th>
        <th>Дата создания</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>
