<?php
/** @var string $url */
/** @var array<int, string> $errors */
/** @var Slim\Interfaces\RouteParserInterface $routeParser */
?>

<div class="row">
    <div class="col-lg-10 mx-auto">
        <div class="bg-dark text-white p-5 rounded-3">
            <h1 class="display-3">Анализатор страниц</h1>
            <p class="lead">
                Бесплатно проверяйте сайты на SEO пригодность
            </p>
            <form action="<?= htmlspecialchars($routeParser->urlFor('urls.store')) ?>" method="post" class="row g-2 mt-3">
                <div class="col-md-8">
                    <input
                            type="text"
                            name="url"
                            value="<?= htmlspecialchars($url ?? '') ?>"
                            class="form-control form-control-lg <?= !empty($errors) ? 'is-invalid' : '' ?>"
                            placeholder="https://www.example.com"
                            required
                    >
                    <?php if (!empty($errors)): ?>
                        <div class="invalid-feedback">
                            <?= htmlspecialchars($errors[0]) ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        Проверить
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>