<?php
/** @var string $homeUrl */
/** @var string $urlsUrl */
/** @var string|null $flash */
/** @var string|null $errorFlash */
/** @var string $content */
?>

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link rel="icon" href="/favicon.ico">
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
        crossorigin="anonymous"
    >
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="<?= htmlspecialchars($homeUrl) ?>">Анализатор страниц</a>
        <div class="navbar-nav">
            <a class="nav-link active" href="<?= htmlspecialchars($homeUrl) ?>">Главная</a>
            <a class="nav-link" href="<?= htmlspecialchars($urlsUrl) ?>">Сайты</a>
        </div>
    </div>
</nav>

<main class="container-lg mt-3">
    <?php if (null !== $flash): ?>
        <div class="alert alert-success" role="alert">
            <?= htmlspecialchars($flash) ?>
        </div>
    <?php endif; ?>

    <?php if (null !== $errorFlash): ?>
        <div class="alert alert-danger" role="alert">
            <?= htmlspecialchars($errorFlash) ?>
        </div>
    <?php endif; ?>

    <?= $content ?>
</main>
</body>
</html>